### ISSUE TITLE
Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by arc118** [GenieClient/genie3#42]
I was going to try and research this one myself since it had better error description, but FYI caught this today on latest Genie 3 build:

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()
   at GenieClient.FormMain.TriggerVariableChanged(String sVariableName) in C:\Users\Genie Client 3 Program\opensource\genie3\genie3\Forms\FormMain.cs:line 4044
   at GenieClient.FormMain.ClassCommand_EventVariableChanged(String sVariable) in C:\Users\Genie Client 3 Program\opensource\genie3\genie3\Forms\FormMain.cs:line 4117

**Comment by arc118** [comment]
Collection was modified; enumeration operation may not execute.

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()
   at GenieClient.FormMain.Simutronics_EventEndUpdate() in C:\Users\Desktop\Genie Client 3 Program\opensource\genie3\genie3\Forms\FormMain.cs:line 4535
